import type { DraftComposerPolicy } from './report-draft-policy-types.js';

export const DRAFT_COMPOSER_POLICIES: Partial<Record<
  'operations-cockpit' | 'risk-brief' | 'research-brief' | 'solution-overview' | 'talent-showcase',
  DraftComposerPolicy
>> = {
  'operations-cockpit': {
    audienceTone: 'operator-facing',
    minCounts: {
      hero: 1,
      'metric-grid': 1,
      'insight-list': 1,
      chart: 1,
      cta: 1,
    },
    maxCounts: {
      hero: 1,
      'metric-grid': 1,
      'insight-list': 1,
      comparison: 1,
      timeline: 1,
      chart: 2,
      cta: 1,
    },
    preferredOrder: ['hero', 'metric-grid', 'insight-list', 'comparison', 'timeline', 'chart', 'appendix', 'cta'],
    placeholderTitles: {
      cta: '行动建议',
      chart: '关键趋势图',
    },
    semanticMustHaveTitles: ['页面摘要', '关键指标', '风险提醒', '行动建议'],
    evidencePriorityTitles: ['关键指标', '风险提醒', '行动建议'],
    evidenceRequiredTypes: ['metric-grid', 'chart', 'comparison'],
    overflowTargetTypes: {
      chart: 'comparison',
      comparison: 'summary',
      timeline: 'summary',
      'insight-list': 'summary',
    },
  },
  'risk-brief': {
    audienceTone: 'client-facing',
    minCounts: {
      hero: 1,
      'insight-list': 1,
      chart: 1,
      cta: 1,
    },
    maxCounts: {
      hero: 1,
      'insight-list': 2,
      comparison: 1,
      chart: 1,
      cta: 1,
    },
    preferredOrder: ['hero', 'insight-list', 'comparison', 'chart', 'appendix', 'cta'],
    placeholderTitles: {
      'insight-list': '核心风险',
      cta: '应答建议',
    },
    semanticMustHaveTitles: ['页面摘要', '资格风险', '应答建议'],
    evidencePriorityTitles: ['资格风险', '应答建议'],
    evidenceRequiredTypes: ['insight-list', 'comparison', 'chart'],
    overflowTargetTypes: {
      chart: 'appendix',
      comparison: 'appendix',
      'insight-list': 'summary',
    },
  },
  'research-brief': {
    audienceTone: 'analytical',
    minCounts: {
      hero: 1,
      'insight-list': 2,
      chart: 1,
      cta: 1,
    },
    maxCounts: {
      hero: 1,
      'insight-list': 3,
      comparison: 1,
      chart: 2,
      cta: 1,
    },
    preferredOrder: ['hero', 'insight-list', 'comparison', 'chart', 'appendix', 'cta'],
    placeholderTitles: {
      'insight-list': '核心发现',
      cta: '研究建议',
    },
    semanticMustHaveTitles: ['页面摘要', '核心发现', '局限与风险', '行动建议'],
    evidencePriorityTitles: ['核心发现', '局限与风险'],
    evidenceRequiredTypes: ['insight-list', 'comparison', 'chart'],
    overflowTargetTypes: {
      chart: 'appendix',
      comparison: 'appendix',
      'insight-list': 'summary',
    },
  },
  'solution-overview': {
    audienceTone: 'client-facing',
    minCounts: {
      hero: 1,
      comparison: 1,
      timeline: 1,
      chart: 1,
      cta: 1,
    },
    maxCounts: {
      hero: 1,
      'metric-grid': 1,
      comparison: 2,
      timeline: 1,
      chart: 1,
      'insight-list': 1,
      cta: 1,
    },
    preferredOrder: ['hero', 'metric-grid', 'comparison', 'timeline', 'chart', 'appendix', 'cta'],
    placeholderTitles: {
      comparison: '能力模块',
      timeline: '交付路径',
      cta: '行动建议',
    },
    semanticMustHaveTitles: ['页面摘要', '能力模块', '交付路径', '行动建议'],
    evidencePriorityTitles: ['能力模块', '交付路径', '行动建议'],
    evidenceRequiredTypes: ['comparison', 'timeline', 'chart'],
    overflowTargetTypes: {
      chart: 'comparison',
      timeline: 'summary',
      comparison: 'appendix',
      'insight-list': 'summary',
    },
  },
  'talent-showcase': {
    audienceTone: 'candidate-facing',
    minCounts: {
      hero: 1,
      'insight-list': 1,
      timeline: 1,
      comparison: 1,
      cta: 1,
    },
    maxCounts: {
      hero: 1,
      'metric-grid': 1,
      'insight-list': 1,
      timeline: 1,
      comparison: 1,
      chart: 0,
      cta: 1,
    },
    preferredOrder: ['hero', 'metric-grid', 'insight-list', 'timeline', 'comparison', 'appendix', 'cta'],
    placeholderTitles: {
      timeline: '项目经历',
      comparison: '代表案例',
      cta: '联系建议',
    },
    semanticMustHaveTitles: ['页面摘要', '核心优势', '项目经历', '代表案例', '联系建议'],
    evidencePriorityTitles: ['核心优势', '项目经历', '代表案例'],
    evidenceRequiredTypes: ['timeline', 'comparison', 'metric-grid'],
    overflowTargetTypes: {
      chart: 'comparison',
      comparison: 'appendix',
      timeline: 'summary',
      'insight-list': 'summary',
    },
  },
};
